version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: rion
      POSTGRES_PASSWORD: rion1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server 
    restart: always

volumes:
  postgres_data:
  redis_data:
