import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import { Geist_Mono } from 'next/font/google';
import { Toaster } from 'sonner';
import ThemeProvider from '~/components/providers/theme-provider';
import { TRPCReactProvider } from '~/trpc/react';

import '~/styles/globals.css';

const geistMono = Geist_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistMono.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Toaster pauseWhenPageIsHidden richColors theme="dark" />
        </ThemeProvider>
      </body>
    </html>
  );
}
